apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: email-service
profiles:
  - name: develop
    build:
      artifacts:
        - image: harbor.ccpadmin.cuemby.io/ccp-development/by-email-notification
          docker:
            dockerfile: Dockerfile
            buildArgs:
              GITHUB_TOKEN: '{{.GITHUB_TOKEN}}'
              REPO_PROTOS: '{{.REPO_PROTOS}}'
      local:
        useDockerCLI: true
        useBuildkit: true
    deploy:
      kustomize:
        paths:
        - k8s/develop