apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
  namespace: ccp-developer
spec:
  selector:
   matchLabels:
    app: email-service
  replicas: 1
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: cuemby/ccp-email-notification-service:9
          imagePullPolicy: IfNotPresent     
          ports:
            - containerPort: 50051
              name: emailport
          resources:
            limits:
              memory: 512Mi
              cpu: "0.1"
            requests:
              memory: 256Mi
              cpu: "0.05"
          envFrom:
            - secretRef:
                name: email-service-secrets