apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  #clusterIP: 10.4.2.128
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
      name: grpc-email
  selector:
    app: email-service