apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
  namespace: ccp-beta
spec:
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: cuemby/by-email-notification:v0.0.9-staging
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: emailport
          resources:
            limits:
              memory: 512Mi
              cpu: '0.1'
            requests:
              memory: 256Mi
              cpu: '0.05'
          envFrom:
            - secretRef:
                name: email-service-secrets
