name: CI

on:
  push:
    branches:
        - "iariza/fix/argocd"

env:
  REGISTRY: hub.docker.com


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.PSW_DOCKER_USER }}
        password: ${{ secrets.PSW_DOCKER }}

    - name: clone submodule
      uses: actions/checkout@v3
      with:
        repository: cuemby/ccp-sdk.git
        ref: "dev"
        token: ${{ secrets.DEPLOY_VAULT }}
        path: ccp-sdk

    - name: clone submodule
      uses: actions/checkout@v3
      with:
        repository: cuemby/by-go-utils.git
        ref: "dev-1"
        token: ${{ secrets.DEPLOY_VAULT }}
        path: by-go-utils

    - name: temp modify go.mod
      run: |
        echo "replace github.com/cuemby/ccp-sdk  => ./ccp-sdk" >> go.mod
        echo "replace github.com/cuemby/by-go-utils  => ./by-go-utils" >> go.mod
        echo "doneccp-sdk"

    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cuemby/ccp-email-notification-service:dev