name: Frontend lint/test with cache

on: 
  push:
    branches: 
      - main
      - staging
      - dev

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: deps-node-modules-${{ hashfiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint Frontend Code
        run: npm run lint

  test-project:
    runs-on: ubuntu-latest
    needs: lint-project
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: deps-node-modules-${{ hashfiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Unit Tests
        id: run-frontend-tests
        run: npm run test:unit
